# Generated by Django 5.1.4 on 2025-01-13 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rag_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
